name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build the app
        run: CI=false npm run build

      - name: Deploy to Hostinger via FTP (clean + upload)
        env:
          HOSTINGER_FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}
          HOSTINGER_FTP_USER: ${{ secrets.HOSTINGER_FTP_USER }}
          HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -d -e "set ftp:ssl-allow no; mirror -R ./dist /public_html; quit" -u $HOSTINGER_FTP_USER,$HOSTINGER_FTP_PASSWORD $HOSTINGER_FTP_HOST
